### ISSUE TITLE
Error returned by NRT server when data requested are not available is not the same as the archive server

### ISSUE THREAD

**Issue by rumachan** [GeoNet/fdsn#117]
I am doing this with Python 2.7 and the ObsPy module.

When I request data from the archive server that it does not contain (such as from 2018) I get a sensible error message, but from the near real-time server the message is not what is expected; it does not tell me that no data are available. If I request data held by the near real-time server, it is returned successfully.

arc_client = 'http://beta-service.geonet.org.nz'
nrt_client = 'http://fdsn-ws-nrt.ap-southeast-2.elasticbeanstalk.com'
t = UTCDateTime('2018-10-26')

client = Client(arc_client)
st = client.get_waveforms('NZ', 'KRVZ', '10', 'EHZ', t, t + 3600)
---------------------------------------------------------------------------
FDSNException                             Traceback (most recent call last)
<ipython-input-28-67e16cc54cbc> in <module>()
      1 client = Client(arc_client)
----> 2 st = client.get_waveforms('NZ', 'KRVZ', '10', 'EHZ', t, t + 3600)

/usr/lib/python2.7/dist-packages/obspy/clients/fdsn/client.py in get_waveforms(self, network, station, location, channel, starttime, endtime, quality, minimumlength, longestonly, filename, attach_response, **kwargs)
    734         # Gzip not worth it for MiniSEED and most likely disabled for this
    735         # route in any case.
--> 736         data_stream = self._download(url, use_gzip=False)
    737         data_stream.seek(0, 0)
    738         if filename:

/usr/lib/python2.7/dist-packages/obspy/clients/fdsn/client.py in _download(self, url, return_string, data, use_gzip)
   1340         # No data.
   1341         if code == 204:
-> 1342             raise FDSNException("No data available for request.", server_info)
   1343         elif code == 400:
   1344             msg = ("Bad request. If you think your request was valid "

FDSNException: No data available for request.
Detailed response of server:

** And from the NRT client **
client = Client(nrt_client)
st = client.get_waveforms('NZ', 'KRVZ', '10', 'EHZ', t, t + 3600)
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-29-bf0c55d8e84f> in <module>()
      1 client = Client(nrt_client)
----> 2 st = client.get_waveforms('NZ', 'KRVZ', '10', 'EHZ', t, t + 3600)

/usr/lib/python2.7/dist-packages/obspy/clients/fdsn/client.py in get_waveforms(self, network, station, location, channel, starttime, endtime, quality, minimumlength, longestonly, filename, attach_response, **kwargs)
    740             data_stream.close()
    741         else:
--> 742             st = obspy.read(data_stream, format="MSEED")
    743             data_stream.close()
    744             if attach_response:

<decorator-gen-164> in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, **kwargs)

/usr/lib/python2.7/dist-packages/obspy/core/util/decorator.py in _map_example_filename(func, *args, **kwargs)
    296                         except IOError:
    297                             pass
--> 298         return func(*args, **kwargs)
    299     return _map_example_filename
    300 

/usr/lib/python2.7/dist-packages/obspy/core/stream.py in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, **kwargs)
    207         try:
    208             # first try reading directly
--> 209             stream = _read(pathname_or_url, format, headonly, **kwargs)
    210             st.extend(stream.traces)
    211         except TypeError:

<decorator-gen-165> in _read(filename, format, headonly, **kwargs)

/usr/lib/python2.7/dist-packages/obspy/core/util/decorator.py in uncompress_file(func, filename, *args, **kwargs)
    146     """
    147     if not isinstance(filename, (str, native_str)):
--> 148         return func(filename, *args, **kwargs)
    149     elif not os.path.exists(filename):
    150         msg = "File not found '%s'" % (filename)

/usr/lib/python2.7/dist-packages/obspy/core/stream.py in _read(filename, format, headonly, **kwargs)
    270     """
    271     stream, format = _read_from_plugin('waveform', filename, format=format,
--> 272                                        headonly=headonly, **kwargs)
    273     # set _format identifier for each element
    274     for trace in stream:

/usr/lib/python2.7/dist-packages/obspy/core/util/base.py in _read_from_plugin(plugin_type, filename, format, **kwargs)
    460         raise TypeError(msg % (format_ep.name, ', '.join(eps)))
    461     # read
--> 462     list_obj = read_format(filename, **kwargs)
    463     return list_obj, format_ep.name
    464 

/usr/lib/python2.7/dist-packages/obspy/io/mseed/core.py in _read_mseed(mseed_object, starttime, endtime, headonly, sourcename, reclen, details, header_byteorder, verbose, **kwargs)
    268         bo = None
    269 
--> 270     info = util.get_record_information(mseed_object, endian=bo)
    271 
    272     # Map the encoding to a readable string value.

/usr/lib/python2.7/dist-packages/obspy/io/mseed/util.py in get_record_information(file_or_file_object, offset, endian)
    321     else:
    322         info = _get_record_information(file_or_file_object, offset=offset,
--> 323                                        endian=endian)
    324     return info
    325 

/usr/lib/python2.7/dist-packages/obspy/io/mseed/util.py in _get_record_information(file_object, offset, endian)
    443         except:
    444             endian = "<"
--> 445             values = unpack(fmt(endian), data)
    446             starttime = _parse_time(values)
    447     else:

error: unpack requires a string argument of length 28

**Comment by nbalfour** [comment]
Thanks Steve. 

I would like the NRT service to return a "no data" error when the start date of the request is later than the present time (in the future). 

@gclitheroe, can you or one of your team please make this change. Thanks

**Comment by gclitheroe** [comment]
@rumachan - this should be sorted.  Please could you test it out and close the issue if it now works correctly?

**Comment by rumachan** [comment]
@gclitheroe  I now get the same response from both servers. Thanks.
