### ISSUE TITLE
FDSN archive to production

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#119]
Please make the necessary changes to move FDSN archive service to production on 06/11/2017

**Comment by quiffman** [comment]
The DNS change has been made.
Depending on users' nameserver settings this will either already be apparent, or could take up to a day for the change to propagate.

--
Richard Guest - GeoNet Platform Manager
GNS Science - Te Pu Ao
M +64-27-415-1417 :: T +64-4-570-1444 :: F +64-4-570-4600
1 Fairway Drive, Avalon, PO Box 30-368, Lower Hutt, 5040, New Zealand.
http://www.gns.cri.nz/who/staff/2658.html

________________________________
