### ISSUE TITLE
Station bug?

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/fdsn#121]
I think this might be a bug?  If I have a `channel` parameter in the query I get results e.g.,

`curl -v "https://beta-service.geonet.org.nz/fdsnws/station/1/query?starttime=2017-11-05T00:00:00&channel=20BNZ"`

but if I add the `level` query parameter I get no results e.g.,

`curl -v "https://beta-service.geonet.org.nz/fdsnws/station/1/query?level=response&starttime=2017-11-05T00:00:00&channel=20BNZ"`

the level parameter seems to work ok without the `channel` query parameter e.g.,

`curl -v "https://beta-service.geonet.org.nz/fdsnws/station/1/query?level=response&starttime=2017-11-05T00:00:00"`

**Comment by nbalfour** [comment]
Remove the location code from the channel filter so that it is just "BNZ". There is a separate parameter for the location code.

**Comment by gclitheroe** [comment]
yep - my error.   The other bit of confusion is in #123 

Closing this.
