### ISSUE TITLE
Link fails from web page

### ISSUE THREAD

**Issue by iceseismic** [GeoNet/fdsn#127]
Inside  www.geonet.org.nz/data/tools/FDSN   under "Station"  the documentation currently gives an example request line : 
![image](https://user-images.githubusercontent.com/831424/32925100-07dc3a82-cba5-11e7-9f0c-4442a670a4c7.png)

This link fails for me,  with a  "404 Not Found" error

**Comment by nbalfour** [comment]
My apologies. I left out a semi-colon on the webpage after the https

It should be https://service.geonet.org.nz/fdsnws/station/1/query?latitude=-42.693&longitude=173.022&maxradius=0.5 

I will fix the website
