### ISSUE TITLE
FDSN not recognising some event ID's

### ISSUE THREAD

**Issue by jristau** [GeoNet/fdsn#151]
I've written a script to retrieve data for moment tensor solutions based on the event ID. It's basically an FDSN version of a script I used for CWB. It works fine for SC3 or CUSP ID's, but I've found there is a period around 2010-2011 where FDSN doesn't recognise the event ID, e.g. 3468575 for the February 2011 Christchurch earthquake.

I'm positive that I'm using the correct CUSP ID. I've compared it to QuakeML and output from quake search and the ID's are correct. In addition, if I use my old CWB script with the same event ID I get the data without a problem.

I've tried older events with CUSP ID's, e.g. from 2009, and I can retrieve that data with FDSN without a problem using my script. I don't know the exact date range where the problem exists, but at the end of 2009 I can retrieve data, and by the end of 2011 it's working again. So sometime in 2010-2011.

Cheers
John

**Comment by ozym** [comment]
@jristau you will need to give some more details, a good example would be the exact request line that you are using. Also any error messages that may be coming back. The goal is to replicate the error at this end (without the script) so it can be followed through the system.  At the moment it's not clear whether the problem is with the CUSP ID or whether it is with the underlying data (and associated meta data).

**Comment by jristau** [comment]
The event ID problem seems to have gone away for most events, but there are still some where it doesn't work. Here is an example using ObsPy/Python.

from obspy import UTCDateTime
from obspy.clients.fdsn import Client as FDSN_Client
client=FDSN_Client("GEONET")
cat=client.get_events(eventid="3468575")

This produces the following message:
**Traceback (most recent call last):
  File "./FDSNtest.py", line 13, in <module>
    cat=client.get_events(eventid="3468575")
  File "/home/jristau/scratch/anaconda3/lib/python3.4/site-packages/obspy/clients/fdsn/client.py", line 415, in get_events
    data_stream = self._download(url)
  File "/home/jristau/scratch/anaconda3/lib/python3.4/site-packages/obspy/clients/fdsn/client.py", line 1338, in _download
    raise FDSNException("No data available for request.", server_info)
obspy.clients.fdsn.header.FDSNException: No data available for request.
Detailed response of server:**

Note that after "Detailed response of server:" there is no message.
Other event ID's where I have seen this problem are 3468581 and 3446638. For other ID's, CUSP or SeisComP3, I don't have a problem. If I request the data using the appropriate date/time I can retrieve the data - it's only using the event ID where it doesn't work.

I have also noticed that during the period 06/12/2010 to 31/12/2010 there is no broadband data available,  even if I request it using the date/time. As an example:

from obspy import UTCDateTime
from obspy.clients.fdsn import Client as FDSN_Client
client=FDSN_Client("GEONET")
t=UTCDateTime("2010-12-06T00:00:00.000")
st=client.get_waveforms("NZ","LTZ","10","HH?",t,t + 300)
st.plot()

Gives the message:
**Traceback (most recent call last):
  File "./FDSNtest.py", line 16, in <module>
    st=client.get_waveforms("NZ","LTZ","10","HH?",t,t + 300)
  File "/home/jristau/scratch/anaconda3/lib/python3.4/site-packages/obspy/clients/fdsn/client.py", line 732, in get_waveforms
    data_stream = self._download(url, use_gzip=False)
  File "/home/jristau/scratch/anaconda3/lib/python3.4/site-packages/obspy/clients/fdsn/client.py", line 1338, in _download
    raise FDSNException("No data available for request.", server_info)
obspy.clients.fdsn.header.FDSNException: No data available for request.
Detailed response of server:**

All broadband stations give the same message. Outside of that date range I can retrieve broadband data without a problem using those commands.

**Comment by ozym** [comment]
There doesn't seem to be any problems with the miniSEED data in the SDS archive, I've re-run the sync for the 2010 linked files.

**Comment by gclitheroe** [comment]
This has been fixed - some events were missing from the DB.   All events have been reloaded.
