### ISSUE TITLE
no data for stations NEZ & WNVZ

### ISSUE THREAD

**Issue by filefolder** [GeoNet/fdsn#152]
not sure if it's just not available or if there's a different problem but i can't seem to pull any miniseed data for these between 2015-2018 via FDSN or CWB (RIP!!)

they're both sp borehole sites, WNVZ at Ruapehu and NEZ at Taranaki.

**Comment by ozym** [comment]
It's probably related to the "location" code that is being used for your query.  The standard short period location code is "10", but when we run sensors on the surface and down a borehole we generally use "11" for the borehole sensor.  For some sites the original surface sensor will have been removed and so there's only data available for location code "11".

**Comment by filefolder** [comment]
ah that's it. that's a bit tricky as the auckland borehole sites are still 10's i think.

**Comment by ozym** [comment]
Great, that's probably because they never had a surface sensor installed prior to the boreholes.

**Comment by filefolder** [comment]
ah right sorry. well the location for these sites is "10" in the station response also. fwiw
