### ISSUE TITLE
FDSN- Event service - Missing events

### ISSUE THREAD

**Issue by francovm** [GeoNet/fdsn#153]
Hi,

I am doing some work with FDSN event service and I realized that there are a couple of missing events there. I am not sure if there is an specific reason for this lack of data.

1 - M 6.2 Christchurch Tue, Feb 22 2011
URL query : 
[ https://service.geonet.org.nz/fdsnws/event/1/query?eventid=3468575](https://service.geonet.org.nz/fdsnws/event/1/query?eventid=3468575)

2-  M 7.2 Darfield (Canterbury) Sat, Sep 4 2010

[https://service.geonet.org.nz/fdsnws/event/1/query?eventid=3366146](https://service.geonet.org.nz/fdsnws/event/1/query?eventid=3366146)

3- M7.8 Dusky Sound Wed, Jul 15 2009

[https://service.geonet.org.nz/fdsnws/event/1/query?eventid=3124785](https://service.geonet.org.nz/fdsnws/event/1/query?eventid=3124785)

4 - M 6.7 Gisborne Thu, Dec 20 2007

[https://service.geonet.org.nz/fdsnws/event/1/query?eventid=2839343](https://service.geonet.org.nz/fdsnws/event/1/query?eventid=2839343)

I tried to listed them by date, but I could not find them either. Probably, there are more missing events that I could not find.

**Comment by francovm** [comment]
Also, these event are currently available using `http://quakeml.geonet.org.nz`, but this one should be deprecated soon.

**Comment by junghao** [comment]
I think this is the same issue as in #151.

**Comment by JonoHanson** [comment]
@junghao has there been any action on this?

**Comment by JonoHanson** [comment]
we also need to think about how we make sure this list is complete (as in, we need to catch all the missing events)

**Comment by salichon** [comment]
These events are available under :
>  http://seiscompml07.s3-website-ap-southeast-2.amazonaws.com/{ID}.xml 
They are all CUSP time events.
 - Is a search over the same day of these returning some other missing events (lower magnitudes) ?

**Comment by gclitheroe** [comment]
This has been fixed - some events were missing from the DB.   All events have been reloaded.

**Comment by JonoHanson** [comment]
sweet!
