### ISSUE TITLE
Getting records in near real time

### ISSUE THREAD

**Issue by bertranddelouis** [GeoNet/fdsn#154]
Hello,
I tried to get near-real time data for an event of NZ Magnitude 3.5, Mon Aug 20 2018 1:56 PM, with fetchdata webservice, with the following script:

---------------------------------
#!/bin/bash

# Set servce base path, change to your own service host
#for pas events: SERVICEBASE="http://service.geonet.org.nz"
SERVICEBASE="http://beta-service-nrt.geonet.org.nz"

# Set all service specific locations using the service base
TIMESERIESWS="${SERVICEBASE}/fdsnws/dataselect/1"
METADATAWS="${SERVICEBASE}/fdsnws/station/1"
EVENTWS="${SERVICEBASE}/fdsnws/event/1"
SACPZWS="${SERVICEBASE}/fdsnws/sacpz/1"
RESPWS="${SERVICEBASE}/fdsnws/resp/1"

export SERVICEBASE TIMESERIESWS METADATAWS EVENTWS SACPZWS RESPWS

exec ../FetchData-2017.164 -N '*' -C 'HH?,BH?,LH?,HN?,BN?,LN?' --radius -30.240:-177.990:7   -s 2018-08-19T07:54:32 -e 2018-08-19T08:06:32 -o data.mseed -m resp.metadata
----------------------------

I obtained no error message but no data:

Received 3.5 MB of metadata in 5.8 seconds (613.6 KB/s)
Processed metadata for 0 channel epochs in 5.9 seconds
No data selections to request
DONE at 2018-08-24 12:14:44

An idea why? Is http://beta-service-nrt.geonet.org.nz operational?

Thanks,

Bertrand Delouis (Géoazur, France)

**Comment by francovm** [comment]
Dear Bertrand,

I apologize for the late response, we already sorted out the bug related with this problem.


If you have further queries, we’ll be happy to assist

Thanks,

Franco
