### ISSUE TITLE
Comprehensive logging for FDSN and FDSN-NRT

### ISSUE THREAD

**Issue by danieldooley** [GeoNet/fdsn#179]
As part of recent performance issues we've realised that we aren't able to see the contents of POST requests in the HTTP logs for FDSN and FDSN-NRT. I think for now the solution is to implement logging at the application level for ALL requests. Mapping IP addresses to the data requested.

Just standard Go logging it fine for now, if cloudwatch isn't an effective place to capture these I'll investigate moving the logs into S3.

Could someone please implement this.

**Comment by junghao** [comment]
@danieldooley The post body could be long. Should we truncate it in the log? Say, 2048 chars max.

**Comment by danieldooley** [comment]
The point is to get an idea of the requests being made so we probably want to see all of it to begin with.
