### ISSUE TITLE
Comma separated lists parameters

### ISSUE THREAD

**Issue by junghao** [GeoNet/fdsn#199]
Queries like this
```
https://service.geonet.org.nz/fdsnws/dataselect/1/query?network=NZ&cha=HHZ&loc=10,20&starttime=2011-03-20T06:15:00.000&endtime=2011-03-20T06:20:00.000&sta=WEL
```
Should get result with location 10 and 20. But now it's failing.

FDSN specification:
- network RequiredSelect one or more network codes. Can be SEED network codes or data center defined codes. **Multiple codes are comma-separated**.
- station Required Select one or more SEED station codes. Multiple codes are comma-separated.
- location Required Select one or more SEED location identifiers. Multiple identifiers are comma- separated. As a special case “--“ (two dashes) will be translated to a string of twospace characters to match blank location IDs.
- channel Required Select one or more SEED channel codes. Multiple codes are comma-separated.

**Comment by salichon** [comment]
FYI @rumachan
