### ISSUE TITLE
Events missing from quakesearch 

### ISSUE THREAD

**Issue by segburg** [GeoNet/fdsn#211]
Hi, I noticed that some earthquakes obtained through a fdsn request were missing from the quakesearch result when using the same criteria. The discrepancy seems to kick in from 2015 (see attachment). I extracted earthquakes of M2+ and regional boundaries 163.,-50,183,-32 starting in 2000.

Looping over the years, my quakesearch was:
curl -o quake-M2+${t1}-${t2}.csv 'https://quakesearch.geonet.org.nz/csv?bbox=163.,-50,183,-32&startdate='${t1}'-01-01&enddate='${t2}'-01-01&minmag=2'

The corresponding fdsn search was:
curl -o $dirout/quake-W1fdsn-M2+-${t1}-${t2}.txt 'https://service.geonet.org.nz/fdsnws/event/1/query?minlat=-50&maxlat=-32&minlon=163.&maxlon=172&starttime='${t1}'-01-01&endtime='${t2}'-01-01&minmagnitude=2&format=text'
....
and repeated for minlongitudes up to 180 degrees because of the annoying limitation on earthquake numbers.

[missing_eqs_2015_2020.txt](https://github.com/GeoNet/fdsn/files/6232400/missing_eqs_2015_2020.txt)

**Comment by bpeng** [comment]
I had a quick check, seems the missing quakes are either `deleted` or outside the `bbox`,  **QuakeSearch** doesn't return deleted quakes while fdsn may not have that condition. 
@segburg  @sue-h-gns

**Comment by segburg** [comment]
1. Would you be able to investigate whether fdsn includes earthquakes that were entirely deleted? This is important to know as our earthquake catalogue needs to be complete and shouldn't include extra events. Which search should I trust?

2. Can you explain why some of the earthquakes would be outside the bounding box when the defined bounding box was the same in the quakesearch and the fdsn search. Both results should depend on the preferred hypocentre location I would think?

**Comment by salichon** [comment]
@segburg Kia Ora
**_ QuakeSearch doesn't return deleted quakes_** --> yeap cos they are not quakes :) Quake serach is only made for the earthquakes so it s a service that is providing a subset of the large "events" data set

**Comment by salichon** [comment]
- List of missing EQ form Dev-team  for record  and future investigation.
[MissingFDSN2QsearchEq.xlsx](https://github.com/GeoNet/fdsn/files/7656788/MissingFDSN2QsearchEq.xlsx)
[MissingFDSN2QsearchEq.xlsx](https://github.com/GeoNet/fdsn/files/7656789/MissingFDSN2QsearchEq.xlsx)

**Comment by sue-h-gns** [comment]
@salichon please take a look at my version, as it allows you to remove the deleted quakes.
Several are also "outside of network interest) there are only 6 in this list that may be an issue. I will look into this further
[MissingFDSN2QsearchEq.xlsx](https://github.com/GeoNet/fdsn/files/7731869/MissingFDSN2QsearchEq.xlsx)

**Comment by sue-h-gns** [comment]
Quakes are deleted or outside of network interest.
