### ISSUE TITLE
Data aged 7-14 days not available from FDSN service

### ISSUE THREAD

**Issue by AdrianBenson** [GeoNet/fdsn#223]
I am seeing a gap in data availabilty via FDSN. 

Data < 7days age are available via https://service-nrt.geonet.org.nz as expected
Data > 14 days are available via https://service.geonet.org.nz as expected
Data 7-14 days age (approx)  are not available from either 

I have run tests on a variety of sations/channels/data etc. and a none are available.
I have a continuously running process that requests data for EYWM,SBAM,APIM,SMHS with a 168h lag (10 day, 1h per request) No data has been returned for a week at least.
 
I have checked with @salichon and the data I require  (Geomagnetic from EYWM, SBAM etc) are definitely available to be served. 

I have not seen this, so perhaps there has been some changes.
If this is now the expected behaviour, then https://www.geonet.org.nz/data/tools/FDSN should be updated to reflect this.

```
$> day=23
$> curl "https://service.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=OPZ&loc=10&start=2021-11-${day}T00:00:00.000&end=2021-11-${day}T01:00:00.000" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
$> day=22
$> curl "https://service.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=OPZ&loc=10&start=2021-11-${day}T00:00:00.000&end=2021-11-${day}T01:00:00.000" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4608    0  4608    0     0   8213      0 --:--:-- --:--:-- --:--:--  8213
```

**Comment by ozym** [comment]
@AdrianBenson could you run these checks again, just working through a disk issue.

**Comment by AdrianBenson** [comment]
@ozym Just ran tests for 23-30. Data were returned OPZ 

```
for day in {23..30}; do curl -sw "2021-11-$day Bytes: %{size_download}\n" "https://service.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=OPZ&start=2021-11-${day}T00:00:00.000&end=2021-11-${day}T00:10:00.000" -o junk.mseed; done
2021-11-23 Bytes: 8192
2021-11-24 Bytes: 8192
2021-11-25 Bytes: 6144
2021-11-26 Bytes: 8192
2021-11-27 Bytes: 8192
2021-11-28 Bytes: 7680
2021-11-29 Bytes: 7680
2021-11-30 Bytes: 8192
```
However tests for EYWM are patchy at best 

```
for day in {25..30}; do curl -sw "2021-11-$day Bytes: %{size_download}\n" "https://service.geonet.org.nz/fdsnws/dataselect/1/query?net=NZ&sta=EYWM&loc=50&channel=LF?&start=2021-11-${day}T00:00:00.000&end=2021-11-${day}T01:00:00.000" -o junk.$day.mseed; done
2021-11-25 Bytes: 10752
2021-11-26 Bytes: 10240
2021-11-27 Bytes: 5632
2021-11-28 Bytes: 512
2021-11-29 Bytes: 5120
2021-11-30 Bytes: 5120
```
- Data 2021-11-25--26 are complete
- Data 2021-11-27-30 are all over the place E.g.

```
msi junk.27.mseed 
NZ_EYWM_50_LFX, 013886, D, 512, 388 samples, 1 Hz, 2021,330,23:58:48.071829
NZ_EYWM_50_LFY, 013758, D, 512, 399 samples, 1 Hz, 2021,330,23:55:43.071829
NZ_EYWM_50_LFZ, 014130, D, 512, 388 samples, 1 Hz, 2021,331,00:06:20.071854
NZ_EYWM_50_LFZ, 014131, D, 512, 384 samples, 1 Hz, 2021,331,00:12:48.071872
NZ_EYWM_50_LFZ, 014132, D, 512, 382 samples, 1 Hz, 2021,331,00:19:12.071865
NZ_EYWM_50_LFZ, 014133, D, 512, 371 samples, 1 Hz, 2021,331,00:25:34.071860
NZ_EYWM_50_LFZ, 014134, D, 512, 371 samples, 1 Hz, 2021,331,00:31:45.071860
NZ_EYWM_50_LFZ, 014135, D, 512, 359 samples, 1 Hz, 2021,331,00:37:56.071860
NZ_EYWM_50_LFZ, 014136, D, 512, 348 samples, 1 Hz, 2021,331,00:43:55.071860
NZ_EYWM_50_LFZ, 014137, D, 512, 346 samples, 1 Hz, 2021,331,00:49:43.071860
NZ_EYWM_50_LFZ, 014138, D, 512, 352 samples, 1 Hz, 2021,331,00:55:29.071860
``
Only 1 packet for LFX, 0 for LFY etc

**Comment by sue-h-gns** [comment]
@salichon, I believe Mark fixed this (it was a full disk I believe), can you please confirm and close, or let us know what further action needs to be taken?

**Comment by salichon** [comment]
@AdrianBenson have you been trhough this yet ?
If it ll all sorted please inform here or report any  continuing issues,
thanks!
Jjerome

**Comment by stuartmead** [comment]
Tagging onto this, it appears as if data ~10 days age is not available through service.geonet.org.nz. I have checked a variety of stations for 15 January and come up empty. Is this a similar issue?

**Comment by ozym** [comment]
Yes, a similar issue but a different cause. The system is busy working through the backlog of processing, which I expect to be done in the next few hours.

**Comment by sue-h-gns** [comment]
NRT service now giving 8 days of data, so overlap should prevent this issue in the future
