### ISSUE TITLE
seismic data waveforms incomplete for 2023-01-31 to 2023-02-02

### ISSUE THREAD

**Issue by segburg** [GeoNet/fdsn#244]
Kia ora, 

I am using waveform data stored under /geonet/seismic/2023/NZ. We noticed that waveforms for days within 2023-01-31 to 2023-02-02 are segmented into short segments of around 5s length. I looked at the waveforms of a few broadband and strong motion stations, and they happen to all display this problem. Could the waveform data for those three days be recreated ?

Many thanks

**Comment by elidana** [comment]
Kia ora @segburg , thanks a lot for that!!

Would you mind confirming if you see the same issue if you use waveform for this location? 
`s3://geonet-open-data/waveforms/miniseed/2023/`

the files are arranged slightly differently (see https://github.com/GeoNet/data-tutorials/tree/main/AWS_Open_Data#wave-miniseed for some more details)
Some examples on how to use this location on AWS below (from a unix terminal, and using a command line), happy to help with further commands if you wish!

### to list the content
`aws s3 ls --no-sign-request s3://geonet-open-data/waveforms/miniseed/2023/`

for example, to list the miniseed waveform available for WTAZ for the day 2023-01-31 (doy 031), you can:
```
$> aws s3 ls --no-sign-request s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/
```
and you will see an output like
```
2023-02-06 03:00:55   20492800 2023.031.WTAZ.12-HHE.NZ.D
2023-02-06 03:00:54   20629504 2023.031.WTAZ.12-HHN.NZ.D
2023-02-06 03:00:55   20166144 2023.031.WTAZ.12-HHZ.NZ.D
2023-02-06 03:01:06     214528 2023.031.WTAZ.12-LHE.NZ.D
2023-02-06 03:00:51     214528 2023.031.WTAZ.12-LHN.NZ.D
2023-02-06 03:01:08     213504 2023.031.WTAZ.12-LHZ.NZ.D
```

to copy the miniseed file `2023.031.WTAZ.12-HHE.NZ.D` to your local folder (`.`) you can

```
$> aws s3 cp --no-sign-request s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-HHE.NZ.D .
```
and stdout will be
```
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-HHE.NZ.D to ./2023.031.WTAZ.12-HHE.NZ.D
```

To copy the entire day of WTAZ data to your local folder, you can run
```
$ aws s3 sync --no-sign-request s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/ .
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-LHE.NZ.D to ./2023.031.WTAZ.12-LHE.NZ.D
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-LHN.NZ.D to ./2023.031.WTAZ.12-LHN.NZ.D
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-LHZ.NZ.D to ./2023.031.WTAZ.12-LHZ.NZ.D
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-HHN.NZ.D to ./2023.031.WTAZ.12-HHN.NZ.D
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-HHE.NZ.D to ./2023.031.WTAZ.12-HHE.NZ.D
download: s3://geonet-open-data/waveforms/miniseed/2023/2023.031/WTAZ.NZ/2023.031.WTAZ.12-HHZ.NZ.D to ./2023.031.WTAZ.12-HHZ.NZ.D
```

(and same for the entire day, for all stations)


Hope this helps, and please let us know if you still see the same short segments popping up!

Thanks!

Elisabetta

**Comment by segburg** [comment]
Thanks Elisabetta,
I had downloaded the data through fdsn. The original miniseed data is fine. The copy of the miniseed files to /geonet/seismic for those three days only however may have had interruptions, hence the segmentation. We were hoping to access the /geonet/seismic archive through seiscomp. I can circumvent this problem in a lenghty and cumbersome manner, whereas this is a quick fix for GeoNet. In addition, I thought that someone else may also need this data and encounter the same issue . I could copy over the healthy files but don't have the permissions to do so.

**Comment by elidana** [comment]
hello @segburg , 
I have just realized we could probably use the GeoNet help repository for this conversation, that is not strictly related to our FDSN webservice. I am closing this, and will open a separate ticket on the correct location. Will tag you once done.
