### ISSUE TITLE
StationXML process

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/fdsn#34]
I've deployed the version of FDSN ws that includes the station service.  

- This uses a station.xml file for it's input.  
- I generated the file we're using from https://github.com/GeoNet/delta/tree/master/tools/stationxml
- I've put it in s3://api.geonet.org.nz/station.xml

This is temporary and needs moving and automating as the delta and archive process shakes out.

**Comment by nbalfour** [comment]
I have noticed that the current stationXML used for beta returns sites that have no sensor installed.  Such as SR057 and sites that have creation dates in the future. 
@quiffman @ozym we need to have a bit of a discussion around what we should include in the stationXML.

**Comment by ozym** [comment]
Yes, the current StationXML reflects what's in the delta repo and needs cleaning both in the repo and in the selections used for the FDSN services.  The StationXML used for the waveform service is likely to be different to the one that's used with the station service.

e.g.
https://beta-service.geonet.org.nz/fdsnws/event/1/query?minmagnitude=6&starttime=1971-04-15&endtime=1971-04-16

```
<q:quakeml xmlns:q="http://quakeml.org/xmlns/quakeml/1.2" xmlns="http://quakeml.org/xmlns/bed/1.2">
<script/>
<eventParameters publicID="smi:nz.org.geonet/NA">
<event publicID="smi:nz.org.geonet/1553545">
<amplitude publicID="smi:nz.org.geonet/111963">
<type>AML</type>
<genericAmplitude>
<value>0.032000</value>
</genericAmplitude>
<timeWindow>
<reference>1971-04-15T00:37:26.790Z</reference>
<begin>0</begin>
<end>0</end>
</timeWindow>
<unit>m</unit>
<waveformID stationCode="TUA" networkCode="NZ"/>
<evaluationMode>manual</evaluationMode>
<comment>
<text>timing uncertain</text>
</comment>
</amplitude>
...
<pick publicID="smi:nz.org.geonet/153174">
<time>
<value>1971-04-15T00:38:31.600Z</value>
<lowerUncertainty>0.1</lowerUncertainty>
<upperUncertainty>0.25</upperUncertainty>
</time>
<waveformID stationCode="MNG" networkCode="NZ"/>
<onset>impulsive</onset>
<phaseHint>P</phaseHint>
<polarity>positive</polarity>
<evaluationMode>manual</evaluationMode>
<evaluationStatus>confirmed</evaluationStatus>
</pick>
...
```

These QuakeML picks and magnitues have no waveforms associated with them, but equally they also have no station locations associated with them ...

**Comment by gclitheroe** [comment]
I've switched fdsn-ws over to use the station xml file geonet-meta/stationxml/complete.xml
