### ISSUE TITLE
Test the FDSN event service

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#5]
As the product owner 
I would like to have a select set of users test the complete FDSN event service before it goes to service.geonet.org.nz
So that I can be confident that it will not greatly impact the delivery of existing FDSN services

Acceptance Criteria:
- [x] there is a beta-service.geonet.org.nz set up
- [x] it provides access to the new event service

*remove acceptance criteria:  "it provides access to the existing station and dataselect services" since new services were provided*

**Comment by nbalfour** [comment]
I've been testing this out using both the URL and obspy

The URL seems to be working ok and returns 29 events using the query...

`http://beta-service.geonet.org.nz/fdsnws/event/1/query?minmagnitude=5&starttime=2016-11-13T11:05:00&endtime=2016-11-20T11:05:00&latitude=-42.69&longitude=173.02&maxradius=1`

But the query with obspy:

```
client = FDSN_Client("http://beta-service.geonet.org.nz/")
events = client.get_events(starttime="2016-11-13 11:00:00.000", endtime="2016-11-20 11:00:00.000", minmagnitude=5, longtitude=173.02, latitude=-42.69, maxradius=1)
```

Gets the following error:
`TypeError: The parameter 'maxradius' is not supported by the service.`

[Obspy documentation](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_events.html) says it is supported and our FDSN webservice seems to support it based on this work and the URL test, so I am confused. 

If anyone can shed some light on this that would be great.

**Comment by rumachan** [comment]
You had a typo on 'longtitude', when I correct that I get a similar, but not exactly the same, error
TypeError: The parameter 'longitude' is not supported by the service.

If I use 'IRIS' as the client then it works, so ObsPy is happy with this, as you thought.

**Comment by nbalfour** [comment]
Sorry, that was a typo but the issue still holds and I still get the same error. 

`cat = client.get_events(starttime=starttime, endtime=endtime, minmagnitude=5, longitude=173.02, latitude=-42.69, maxradius=1)`

gives me this (full python error is included this time):
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-2ff829561991> in <module>()
      4 starttime = "2016-11-13 11:00:00.000"
      5 endtime = "2016-11-20 11:00:00.000"
----> 6 cat = client.get_events(starttime=starttime, endtime=endtime, minmagnitude=5, longitude=173.02, latitude=-42.69, maxradius=1)
      7 #cat = client.get_events(eventid="2016p858000")
      8 #print(cat)

C:\Users\natalieb\AppData\Local\Continuum\Anaconda3\lib\site-packages\obspy\clients\fdsn\client.py in get_events(self, starttime, endtime, minlatitude, maxlatitude, minlongitude, maxlongitude, latitude, longitude, minradius, maxradius, mindepth, maxdepth, minmagnitude, maxmagnitude, magnitudetype, includeallorigins, includeallmagnitudes, includearrivals, eventid, limit, offset, orderby, catalog, contributor, updatedafter, filename, **kwargs)
    411 
    412         url = self._create_url_from_parameters(
--> 413             "event", DEFAULT_PARAMETERS['event'], kwargs)
    414 
    415         data_stream = self._download(url)

C:\Users\natalieb\AppData\Local\Continuum\Anaconda3\lib\site-packages\obspy\clients\fdsn\client.py in _create_url_from_parameters(self, service, default_params, parameters)
   1153                         "The parameter '%s' is not supported by the service." \
   1154                         % key
-> 1155                     raise TypeError(msg)
   1156             # Now attempt to convert the parameter to the correct type.
   1157             this_type = service_params[key]["type"]

TypeError: The parameter 'maxradius' is not supported by the service.
```

**Comment by rumachan** [comment]
You are using anaconda3, I'm using my local python (2.7). We have the same issue, except mine picks up on the longitude parameter and your's the maxradius. Query is exactly the same. I am using ObsPy 1.0.3
What other query options are available on beta-service?

**Comment by nbalfour** [comment]
@rumachan, are you asking specifically about the event service on beta?

**Comment by nbalfour** [comment]
@rumachan 
I believe this is what is **not** included so far for the event service:
- [ ] include arrivals
- [ ] include all origins
- [ ] magnitude type
- [ ] include all magnitudes
- [ ] limit
- [ ] offset
- [ ] catalog
- [ ] contributor
- [ ] updatedafter
- [ ] nodata

For MVP we were focusing on required parameters but some of these might be required by our end users. Please let me know if there are any that you would find useful if they were included.

**Comment by junghao** [comment]
Ok I'll do _updateafter_ and _nodata_ .

**Comment by junghao** [comment]
@nbalfour 
Would you please help me to clarify in defining _updatedafter_ since the specification doesn't elaborate which(and how) one(s) should be checked when applying _updatedafter_.
Below are some date-related fields:

For event query -
* ModificationTime and OriginTime

For station query -
* CreationDate and TermintationDate
* InstallationDate, CalibrationDate and RemovalDate
* BeginEffectiveTime and EndEffectiveTime
* StartDate and EndDate

**Comment by nbalfour** [comment]
For the event query, use the ModificationTime

At this stage please don't implement this parameter for the station query. I don't understand at the moment what would be a useful parameter to use and it sounds like different data centers define this in a different way.

**Comment by gclitheroe** [comment]
There should be a column for this in the db aready

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
