### ISSUE TITLE
Add more optional parameters to the event service

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#51]
This is probably not MVP but I can image some users will want this feature added:

As a seismologist, I want to search for all earthquakes within a defined distance range from an station, so I know what earthquakes to request data for.

- [x] Add area circle search using optional parameters: latitude, longitude, minradius, maxradius to fdsn event service

**Comment by gclitheroe** [comment]
to deploy

**Comment by nbalfour** [comment]
@mabznz can you please test this new option for the radius search?

**Comment by nbalfour** [comment]
@mabznz, this is where I got but I put it in the wrong issue

've been testing this out using both the URL and obspy

The URL seems to be working ok and returns 29 events using the query...

http://beta-service.geonet.org.nz/fdsnws/event/1/query?minmagnitude=5&starttime=2016-11-13T11:05:00&endtime=2016-11-20T11:05:00&latitude=-42.69&longitude=173.02&maxradius=1

But the query with obspy:

client = FDSN_Client("http://beta-service.geonet.org.nz/")
events = client.get_events(starttime="2016-11-13 11:00:00.000", endtime="2016-11-20 11:00:00.000", minmagnitude=5, longtitude=173.02, latitude=-42.69, maxradius=1)
Gets the following error:
TypeError: The parameter 'maxradius' is not supported by the service.

Obspy documentation says it is supported and our FDSN webservice seems to support it based on this work and the URL test, so I am confused.

See #5 for full discussion

**Comment by mabznz** [comment]
After checking the python code it was the discovery of the event services parameters it was doing against the wadl that was the problem. Any client doing that would get an issue.

The event wadl at http://beta-service.geonet.org.nz/fdsnws/event/1/application.wadl is not the right one.

**Comment by gclitheroe** [comment]
@junghao - it sounds like the maxradius parameter needs adding to the wadl?

**Comment by gclitheroe** [comment]
Howard has updated the wadl for the event service and this is now deployed.  Please could you give this a test?

**Comment by mabznz** [comment]
Have tested and the optional parameters min/max radius have been added to wadl so the original query works through obspy.

However their are still some optional parameters that are allowed by present event service
http://service.geonet.org.nz/fdsnws/event/1/application.wadl
that are not explicitly allowed by new event service
http://beta-service.geonet.org.nz/fdsnws/event/1/application.wadl

eg:
includeallorigins

@nbalfour Decision needed on do we match the old event service to new in terms of what parameters you can query service by (and not break existing clients that may expect them.)

**Comment by nbalfour** [comment]
@mabznz, we don't provide any event service for service.geonet.org.nz so the documentation should probably not even exist

**Comment by junghao** [comment]
I can add includeallorigins, includeallmagnitudes, and includearrivals to wadl so obspy wouldn't crash. However, you'll get bad request error if you sent a query with those parameter set true.
Is that ok with you?

**Comment by mabznz** [comment]
@nbalfour @junghao have tested the parameters as listed as available in the WADL at http://beta-service.geonet.org.nz/fdsnws/event/1/application.wadl

Could only see two minor issues:

1. orderby parameter works for time-asc, but not magnitide-asc
2. format=text does not response as text even though its listed in WADL. Option needs removing.

Otherwise all good for all optional parameters.  From the FDSN spec for optional parameters not listed in GeoNet WADL service now return "$ is not supported" which is great.

http://beta-service.geonet.org.nz/fdsnws/event/1/query?offset=1&starttime=2016-11-20T10:00:00&endtime=2016-11-20T11:00:00

**Comment by nbalfour** [comment]
I have been thinking and researching a bit about the text output as a format option. There is no set way of doing this. The most common output format is before. 

The output from the IRIS service and USGS service looks like this:
``
#EventID | Time | Latitude | Longitude | Depth/km | Author | Catalog | Contributor | ContributorID | MagType | Magnitude | MagAuthor | EventLocationName
609301|1997-10-14T09:53:11|-22.1447|-176.7203|105.4|ISC|ISC|ISC|1047281|mw|7.8|NEIC|SOUTH OF FIJI ISLANDS
``
Since the end users have not requested this feature and QuakeSearch essentially provides this information in a text format, I am going to make the decision not to included this feature in the service at this time.

**Comment by nbalfour** [comment]
@junghao can you please look into the magnitude-asc issue. In Byron's test it returned the QuakeML but the order of the earthquakes was still in magnitude descending.

**Comment by nbalfour** [comment]
@mabznz can you please test the magnitude-asc option? It looks like it was resolved in the last pull request  https://github.com/GeoNet/fdsn/pull/82

**Comment by mabznz** [comment]
@nbalfour magnitude-asc option now working correctly
