### ISSUE TITLE
Test reliability of FDSN dataselect service

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#7]
As a tester
I want to run appropriate tests of the dataselect service
So that I can make sure the service is fulfilling the requirements of our end users

Acceptance criteria:
- [ ] collate problematic fdsn queries to use as tests
- [x] run queries on the new fsdn data select service
- [x] queries return meaningful error instead of handing if they fail

**Comment by sue-h-gns** [comment]
@nbalfour  do you know if there are any outstanding issues regarding the FDSN service, or can we close this old issue

**Comment by nbalfour** [comment]
@sue-h-gns I think this is being worked on elsewhere and is captured in this ticket https://github.com/GeoNet/tickets/issues/5138
So, in my opinion we should close this ticket.
