### ISSUE TITLE
base URL in wadl resources

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/fdsn#70]
hi Howard,

I doubt this has much to do with the SC3 issues.  I noticed that the resources base URL is wrong in our wadl files for beta, it's wrong on service.geonet as well.

http://beta-service.geonet.org.nz/fdsnws/dataselect/1/application.wadl
http://fdsn-ws-nrt.ap-southeast-2.elasticbeanstalk.com/fdsnws/dataselect/1/application.wadl
http://service.geonet.org.nz/fdsnws/dataselect/1/application.wadl
http://service.iris.edu/fdsnws/dataselect/1/application.wadl

**Comment by junghao** [comment]
@gclitheroe 
This issue is resolved by https://github.com/GeoNet/fdsn/pull/73. We'll have to export HOST_CNAME environment variable to the  running beta service to work.

**Comment by gclitheroe** [comment]
Done (based on the above comment)
