### ISSUE TITLE
Tool to generate bucket upload notifications

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/fdsn#75]
Hi Howard,

Please could your write a command line tool in this repo?  I suggest the name `cmd/s3-notify`.  We need to reindex the miniSEED data. The goal of `s3-notify` is to list all the keys matching a prefix in a bucket and then for each object send a notification to an SQS queue.  

Only a partially notification message should be needed in the JSON format used by the consumer, that is here https://github.com/GeoNet/fdsn/blob/master/internal/platform/s3/notification.go

In case it's useful the full message format is here http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

And there is an example at the end of this issue.

There will be hundreds of thousands of objects in the S3 bucket so you will need to handle pagination / continuation when listing the bucket.  If you want to test this out I think you should able to list s3:///seiscompml07 with any creds - it has a lot of objects in it.

Please use command line args (flags) for 

* bucket name
* key prefix
* SQS URL to send the notifications to

Use the regular env var for AWS creds:

* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AWS_REGION=ap-southeast-2

Here is a complete notification message for reference (no leading slash in the key).

```
{  
   "Records":[  
      {  
         "eventVersion":"2.0",
         "eventSource":"aws:s3",
         "awsRegion":"ap-southeast-2",
         "eventTime":"2017-07-18T07:37:23.708Z",
         "eventName":"ObjectCreated:Put",
         "userIdentity":{  
            "principalId":"AWS:AIDAJYYKKSFK62GQJLB4Y"
         },
         "requestParameters":{  
            "sourceIPAddress":"161.65.58.28"
         },
         "responseElements":{  
            "x-amz-request-id":"6CA9E1E7E76A44E9",
            "x-amz-id-2":"OVmhicjfIVCx0mABG5bsTRpOSS3yJSpVVJGm6WNy4QT11sI8mxw1VWBuDN/7mURL/IoW6HLdHKs="
         },
         "s3":{  
            "s3SchemaVersion":"1.0",
            "configurationId":"tf-s3-topic-00e30fd9205671484af8e50bf3",
            "bucket":{  
               "name":"geonet-archive",
               "ownerIdentity":{  
                  "principalId":"A3698EZ2HM37K7"
               },
               "arn":"arn:aws:s3:::geonet-archive"
            },
            "object":{  
               "key":"miniseed/2007/2007.074/URZ.NZ/2007.074.URZ.01-UFC.NZ.D",
               "size":1024,
               "eTag":"30f6ce7e84fd511f1a1fd1d42ff398a9",
               "versionId":"Oru8b1DWpfIb68rCLVZk4bkIj04j2O2h",
               "sequencer":"00596DBAB3A2795B0C"
            }
         }
      }
   ]
}
```

**Comment by junghao** [comment]
@gclitheroe 
Most of the information can be obtained by looping a simple ListObject call which would be very efficient. 
However, the *versionId* info only exists in GetObject calls. So we'll have to download the whole object to get it. 
Is the *versionId* essential to the service?

**Comment by gclitheroe** [comment]
We don't need the versionID  - in this case it's just getting the object at the "head" version - the version id isn't used e.g., https://github.com/GeoNet/fdsn/blob/master/cmd/fdsn-holdings-consumer/main.go#L121
