### ISSUE TITLE
FDSN beta service waveforms do not begin and end at requested times

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#78]
Shifted from [GeoNet/help#41](https://github.com/GeoNet/help/issues/41)

This actually holds true for the current fdsn service as well. The below example uses the obspy fdsn client, which appears to pass arguments properly to urls:
```python
from obspy.clients.fdsn import Client
from obspy import UTCDateTime

client = Client('http://beta-service.geonet.org.nz')
st = client.get_waveforms(
    network='NZ', station='CNGZ', location='*', channel='EHZ',
    starttime=UTCDateTime('2019-09-04T04:00:0:0.000000'), 
    endtime=UTCDateTime('2019-09-04T05:00:00.000000'))
print(st)
1 Trace(s) in Stream:
NZ.CNGZ.10.EHZ | 2016-09-04T04:00:01.308441Z - 2016-09-04T04:59:56.868441Z | 100.0 Hz, 359557 samples
```
While this queries the database accurately (generating the url: `http://beta-service.geonet.org.nz/fdsnws/dataselect/1/query?channel=EHZ&station=CNGZ&starttime=2016-09-04T04%3A00%3A00.000000&location=%2A&endtime=2016-09-04T05%3A00%3A00.000000&network=NZ%27`

The returned data do not start at the requested start-time, nor end at the requested end-time.

It looks like the [FDSN spec](http://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf) states that data can start at the start-time or after (and vice-versa for end-time), but, other services provide data closer to that expected. It would be really nice if the GeoNet FDSN did the same.

I say that this holds for the current FDSN, but that isn't quite true: a similar request using the current FDSN service yields the following data:
```python
1 Trace(s) in Stream:
NZ.CNGZ.10.EHZ | 2016-09-04T03:59:54.568443Z - 2016-09-04T05:00:02.408443Z | 100.0 Hz, 360785 samples
```
In this case, the data do not appear to meet the FDSN specs, both starting before the given time, and ending after the end-time.

Further to this - a more general question, why do GeoNet data not have samples at zero-millisecond times (e.g. the closest sample to the given start-time is actually at 2016-09-04T03:59:59.998443). Is this an accumulated leap-second thing?

**Comment by nbalfour** [comment]
To clarify a couple of points:
- The current FDSN service (service.geonet.org.nz) uses an FDSN webservice implementation that SeisComP3 provides straight out of the box. We don't have much control over what the record length is that it returns. I will say that I like this implementation though because it gives you a bit more than you asked for and you can trim the requested data without having to pad the record. Please note this service will be replace by the new service that we are currently testing.
- Our implementation currently uses the start and end points of the relevant records as is. It doesn't do any pruning or padding to refine the records to the length the user selected. We will investigate to see if there is an easy fix that doesn't impact performance. 
- Please note that the FDSN spec states the following, which is why you will notice such a difference between services.   

> Responses for the	query method:
The	results	of	a	successful	request	shall	be returned	as	a	stream	of	miniSEED by	default, using	the	MIME	type	application/vnd.fdsn.mseed.		The	exact	nature	of	the	miniSEED	returned	by	this	service	is	data	center	dependent,	a	center	may	choose	to	remove	duplicated	data	or	prune	to	the	exact	window	specified	by	the	caller.		The	time	series	is	generally	expected	to	represent	unprocessed,	“raw”	recorded	data	as	supplied	by	the	network	operator	or	data	owner.		A	data	center may	choose	to	return	the	results	in	alternate	formats	as	specified by	the	format	parameter.

**Comment by calum-chamberlain** [comment]
Thanks for those clarifications, agree on the point about it being better to get more data then trim it, and if the new implementation mimics that, that would be fine.

**Comment by nbalfour** [comment]
We discussed the option around trimming data and decided we will just provide more data than requested, which is against the spec but makes more sense. This will allow us to provide data in it's raw form rather than reprocessing data. The end user can then trim the data themselves as part of their processing. 

- [ ] For the dataselect service, please go off spec and provide the records that include the starttime and endtime. So slightly more data than requested time window. Do not trim, pad or reprocess the data.

**Comment by calum-chamberlain** [comment]
That sounds good, thanks guys, and thanks for the 180 degree wrapping (not that I have had a chance to test it yet).

Its still not clear to me why data are not sampled on the second though (or for that matter on the 0.01s for 100Hz data)?

**Comment by gclitheroe** [comment]
For clarity - I had followed the spec originally.  @junghao has now gone "off spec" as requested and I've merged this deployed.

Currently the index is being rebuilt - there are some data from 2016 available for testing but this is not yet complete.

**Comment by gclitheroe** [comment]
Reindexig the archive is complete.  This time window issue can now be reviewed.

**Comment by nbalfour** [comment]
The query now returns slight more than the requested time window. The same as our existing FDSN webservice from SC3. Thanks.
