### ISSUE TITLE
shorthand for queries not functional in beta

### ISSUE THREAD

**Issue by filefolder** [GeoNet/fdsn#79]
hi-- i realise this is trivial but none of the abbreviations (e.g. "minlat" or "start" instead of "minlatitude" or "starttime") are working in beta. the mildest of irritations.

**Comment by nbalfour** [comment]
Can we please add the following abbreviations for parameters that are provided in the spec. 

| Parameter | Abbreviation | Services | 
| ----------- | -------------- | ------- | 
| startime | start | dataselect, event, station |   
| endtime | end | dataselect, event, station |
| network | net | dataselect, station |
| station | sta | dataselect, station |
| channel | chan | dataselect, station |
| minlatitude | minlat | event, station |
| minlongitude | minlon | event, station |
| maxlatitude | minlat | event, station |
| maxlongitude | minlon | event, station |
| latitude | minlat | event, station |
| longitude | minlon | event, station |
| minmagnitude | minmag | event |
| maxmagnitude | minmag | event |
| magnitudetype | magtype | event |

**Comment by junghao** [comment]
Currently station and dataselect support abbrevations but not listed in the wadl file.
For abbrevations for event I'll patch it.

**Comment by nbalfour** [comment]
Thanks @junghao

**Comment by gclitheroe** [comment]
I think this should be resolved.  Please can you check it out and resolve this if it is?

**Comment by nbalfour** [comment]
Works great. Thank you
