### ISSUE TITLE
beta station query not working with format=sc3ml

### ISSUE THREAD

**Issue by filefolder** [GeoNet/fdsn#80]
https://beta-service.geonet.org.nz/fdsnws/station/1/query?level=station&minlatitude=-42&format=sc3ml

doesn't work ("invalid format")

but 

http://service.geonet.org.nz/fdsnws/station/1/query?level=station&minlatitude=-42&format=sc3ml
&
https://beta-service.geonet.org.nz/fdsnws/station/1/query?level=station&minlatitude=-42

produce normal output

**Comment by nbalfour** [comment]
The formats that are supported for the station service at beta-service.geonet.org.nz is **text** and **xml**. Where xml returns FDSNstationXML

sc3ml was returned by service.geonet.org.nz because it uses the SC3 implementation of FDSN webservices.

Are you requesting additional formats?

**Comment by filefolder** [comment]
ah. i don't recall importing xml into seiscomp/sc3 to be too tricky in the past, so no real trouble there, i just assumed it was also an option in beta.

**Comment by nbalfour** [comment]
Are you planning on using the beta fdsn service as a data source for SC3? If so, please note we found a bug in SC3 during testing. Gempa quickly fixed the issue with the latest update of SC3. So please update SC3 before you use FDSN as a source.

**Comment by filefolder** [comment]
thanks i hadn't looked in a while, was still on 2016.333. 

i was hoping that using event data from the fdsn beta will solve an issue with some older (20th century) geonet events not always "finding" station locations in sc3's picker when i imported them via xml. never figured out what was going on there.
