### ISSUE TITLE
fdsn-ws-nrt record select range logic check.

### ISSUE THREAD

**Issue by junghao** [GeoNet/fdsn#86]
We've made the start time - end time filter logic for cmd/fdsn-ws in #78.
Have to check if the nrt service need some change as well.

**Comment by danieldooley** [comment]
Howard's approach to fix this was to take records from the first record that starts *after* the requested 'start_time' till the record before the record that starts after the 'end_time' and then also include the record before the first one (assuming this record contains the start_time).

This is a good solution without having access to the end time or duration of the records (in the fdsn.record table) but may return strange results if the records are not continuous (i.e. there are gaps). The only *perfect* solution would be to also store the end time or duration in the fdsn.record table.
