### ISSUE TITLE
remove format option from event service wadl

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/fdsn#89]
The wadl still has the format option available. Since the only output format that we are supporting is xml it makes sense to remove that option from the wadl for the event service and return an appropriate error if someone tries to use that option. 

Please:
- [ ] remove format option from the event service wadl
- [ ] return an error if someone uses the format option

**Comment by junghao** [comment]
@nbalfour We can support text output for event service. Do you prefer to remove the option from wadl or to support text format?

**Comment by nbalfour** [comment]
@junghao. Ok, let's support the text format since it is documented and most other institutions provide it as part of the service. I originally felt that you can get this information through quakesearch and therefore was unnecessary but given the community using FDSN is fairly use to this service it would save them hunting around for another way to access this information. 

So, yes, please keep it in the wadl and implement it. Let me know if you can't find the documentation for the text format.

**Comment by junghao** [comment]
@nbalfour 
FDSN spec for text format output:
EventID | Time | Latitude | Longitude | Depth/km | Author | Catalog | Contributor | ContributorID | MagType | Magnitude | MagAuthor | EventLocationName

And GeoNet's beta service responses with some different fields in xml:
http://beta-service.geonet.org.nz/fdsnws/event/1/query?eventid=2017p027063

So some field-mapping for text format of event service require clarification :

| FDSN spec field | GeoNet xml field (or some static string)  |
|-----------------| ------------------|
| Author                |                 |
| Catalog | |
| Contributor||
| ContributorID||
| MagAuthor||
| EventLocationName||

Thanks.

**Comment by nbalfour** [comment]
Of course. Some of these fields are static because we don't have multiple agencies contributing to the catalogue. Some of them are not in our QuakeML but might be in the SC3ML, such as, the EventLocationName which is the Geographic description of event location (e.g. Flinn-Engdahl region name).

| FDSN spec field | GeoNet xml field (or some static string)  |
|-----------------| ------------------|
| Author | GNS |
| Catalog | GNS |
| Contributor | GNS |
| ContributorID | event publicID from XML |
| MagAuthor| GNS |
| EventLocationName| we probably have something that will generate this based on the location|

**Comment by junghao** [comment]
@gclitheroe The EventLocationName would require some copy-paste-add-remove from haz/msg/localities which could be messy, is that OK?

**Comment by gclitheroe** [comment]
We done this without the Flinn-Engdahl regions.  We don't have anything to create them at the moment.  We could add this if it's needed.

**Comment by nbalfour** [comment]
The specifications state "Geographic description of event location (e.g. Flinn-Engdahl region name)", so I interpret that as it doesn't have to be Flinn-Engdahl regions. It can be a different description such as the ones on the website. 

Can you please add the event description to the text format output, such as the description we use on the website? This is not urgent.

**Comment by gclitheroe** [comment]
I'm going to make a kit pkg for the localities so this can stay in the backlog till I have done that.

**Comment by gclitheroe** [comment]
This is done e.g., 

http://beta-service.geonet.org.nz/fdsnws/event/1/query?eventid=2017p027063&format=text
