### ISSUE TITLE
Incorrect "other" event type in QuakeML

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/fdsn#96]
The correct QuakeML event type for "other" is "other event", the XSLT is inserting "other".

```
<xs:enumeration value="other event"/>
```

- [x] fix the XSLT here
- [x] bug report the upstream XSLT source
- [x] deploy haz-quake-consumer and 
- [x] update the errored QuakeML in the DB.

**Comment by gclitheroe** [comment]
Waiting for confirmation from Steve that the corrected events load ok in Swarm and then I can close this.

**Comment by rumachan** [comment]
Swarm loads a single event QuakeML file successfully, but I cannot get it to load a multiple event file, such as Kaikoura aftershocks shown as an example on http://www.geonet.org.nz/data/tools/FDSN. But I can read that multiple event QuakeML file into ObsPy okay. I'm left unsure where my problem is.

As Swarm is showing some other odd behaviour and won't load a SED QuakeML file my suspicion is that my problem lies with Swarm and not our QuakeML.

I'm happy you've solved the 'other' problem, so please go ahead and close.
